version: "3"

services:
  challenge-adminer:
    image: adminer
    ports:
      - "8084:8080"
    networks:
      net:
  challenge-db:
    image: postgres:12
    container_name: challenge-db
    volumes:
      - challenge-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      net:

volumes:
  challenge-data:
networks:
  net:

