package com.duviv.challenge.country.model;

public enum CountriesList {
    BD(new Country("Bangladesh", "", "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg?uselang=fr", Continent.ASIE)),
    BE(new Country("Belgium", "", "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Belgium_%28civil%29.svg?uselang=fr", Continent.EUROPE)),
    BF(new Country("Burkina Faso", "", "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg?uselang=fr", Continent.AFRIQUE)),
    BG(new Country("Bulgaria", "", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg?uselang=frs", Continent.EUROPE)),
    BA(new Country("Bosnia and Herzegovina", "", "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg", Continent.EUROPE)),
    BB(new Country("Barbados", "", "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg?uselang=fr", Continent.AMERIQUE)),
    BN(new Country("Brunei", "", "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg?uselang=fr", Continent.ASIE)),
    BO(new Country("Bolivia", "", "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg?uselang=fr", Continent.AMERIQUE)),
    BH(new Country("Bahrain", "", "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg?uselang=fr", Continent.ASIE)),
    BI(new Country("Burundi", "", "https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg?uselang=fr", Continent.AFRIQUE)),
    BJ(new Country("Benin", "", "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg?uselang=fr", Continent.AFRIQUE)),
    BT(new Country("Bhutan", "", "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg?uselang=fr", Continent.ASIE)),
    JM(new Country("Jamaica", "", "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg?uselang=fr", Continent.AMERIQUE)),
    BW(new Country("Botswana", "", "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg?uselang=fr", Continent.AFRIQUE)),
    WS(new Country("Samoa", "", "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg", Continent.OCEANIE)),
    BR(new Country("Brazil", "", "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg?uselang=fr", Continent.AMERIQUE)),
    BS(new Country("Bahamas", "", "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg?uselang=fr", Continent.AMERIQUE)),
    BY(new Country("Belarus", "", "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg?uselang=fr", Continent.EUROPE)),
    BZ(new Country("Belize", "", "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg", Continent.AMERIQUE)),
    RU(new Country("Russia", "", "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg", Continent.EUROPE)),
    RW(new Country("Rwanda", "", "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg", Continent.AFRIQUE)),
    RS(new Country("Serbia", "", "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg", Continent.EUROPE)),
    TL(new Country("East Timor", "", "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg", Continent.ASIE)),
    TM(new Country("Turkmenistan", "", "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg", Continent.ASIE)),
    TJ(new Country("Tajikistan", "", "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg", Continent.ASIE)),
    RO(new Country("Romania", "", "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg", Continent.EUROPE)),
    GW(new Country("Guinea - Bissau", "", "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg", Continent.AFRIQUE)),
    GT(new Country("Guatemala", "", "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg?uselang=fr", Continent.AMERIQUE)),
    GR(new Country("Greece", "", "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg?uselang=fr", Continent.EUROPE)),
    GQ(new Country("Equatorial Guinea", "", "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg?uselang=fr", Continent.AMERIQUE)),
    JP(new Country("Japan", "", "https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg", Continent.ASIE)),
    GY(new Country("Guyana", "", "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg", Continent.AFRIQUE)),
    GE(new Country("Georgia", "", "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg?uselang=fr", Continent.ASIE)),
    GD(new Country("Grenada", "", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg", Continent.AMERIQUE)),
    GB(new Country("United Kingdom", "", "https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_the_United_Kingdom.svg", Continent.EUROPE)),
    GA(new Country("Gabon", "", "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg", Continent.AFRIQUE)),
    SV(new Country("El Salvador", "", "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg", Continent.AMERIQUE)),
    GN(new Country("Guinea", "", "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg", Continent.AFRIQUE)),
    GM(new Country("Gambia", "", "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg?uselang=fr", Continent.AFRIQUE)),
    GH(new Country("Ghana", "", "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg", Continent.AFRIQUE)),
    OM(new Country("Oman", "", "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg", Continent.ASIE)),
    TN(new Country("Tunisia", "", "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg", Continent.AFRIQUE)),
    JO(new Country("Jordan", "", "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg", Continent.ASIE)),
    HR(new Country("Croatia", "", "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg", Continent.EUROPE)),
    HT(new Country("Haiti", "", "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg", Continent.AMERIQUE)),
    HU(new Country("Hungary", "", "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg", Continent.EUROPE)),
    HN(new Country("Honduras", "", "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg", Continent.AMERIQUE)),
    VE(new Country("Venezuela", "", "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg", Continent.AMERIQUE)),
    PS(new Country("Palestinian Territory", "", "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg", Continent.ASIE)),
    PW(new Country("Palau", "", "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg", Continent.OCEANIE)),
    PT(new Country("Portugal", "", "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg", Continent.EUROPE)),
    PY(new Country("Paraguay", "", "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg", Continent.AMERIQUE)),
    IQ(new Country("Iraq", "", "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg", Continent.ASIE)),
    PA(new Country("Panama", "", "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg", Continent.AMERIQUE)),
    PG(new Country("Papua New Guinea", "", "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg", Continent.OCEANIE)),
    PE(new Country("Peru", "", "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg", Continent.AMERIQUE)),
    PK(new Country("Pakistan", "", "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg", Continent.ASIE)),
    PH(new Country("Philippines", "", "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg", Continent.ASIE)),
    PL(new Country("Poland", "", "https://upload.wikimedia.org/wikipedia/commons/1/12/Flag_of_Poland.svg", Continent.EUROPE)),
    ZM(new Country("Zambia", "", "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg", Continent.AFRIQUE)),
    EE(new Country("Estonia", "", "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg", Continent.EUROPE)),
    EG(new Country("Egypt", "", "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg?uselang=fr", Continent.AFRIQUE)),
    ZA(new Country("South Africa", "", "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg", Continent.AFRIQUE)),
    EC(new Country("Ecuador", "", "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg?uselang=fr", Continent.AMERIQUE)),
    IT(new Country("Italy", "", "https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg", Continent.EUROPE)),
    VN(new Country("Vietnam", "", "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg", Continent.ASIE)),
    SB(new Country("Solomon Islands", "", "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg", Continent.OCEANIE)),
    ET(new Country("Ethiopia", "", "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg?uselang=fr", Continent.AFRIQUE)),
    SO(new Country("Somalia", "", "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg", Continent.AFRIQUE)),
    ZW(new Country("Zimbabwe", "", "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg", Continent.AFRIQUE)),
    SA(new Country("Saudi Arabia", "", "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg?uselang=fr", Continent.ASIE)),
    ES(new Country("Spain", "", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg", Continent.EUROPE)),
    ER(new Country("Eritrea", "", "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg", Continent.AFRIQUE)),
    ME(new Country("Montenegro", "", "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg", Continent.EUROPE)),
    MD(new Country("Moldova", "", "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg", Continent.EUROPE)),
    MG(new Country("Madagascar", "", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg", Continent.AFRIQUE)),
    MA(new Country("Morocco", "", "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg?uselang=fr", Continent.AFRIQUE)),
    MC(new Country("Monaco", "", "https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg", Continent.EUROPE)),
    UZ(new Country("Uzbekistan", "", "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg", Continent.ASIE)),
    MM(new Country("Myanmar", "", "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg", Continent.ASIE)),
    ML(new Country("Mali", "", "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg?uselang=fr", Continent.AFRIQUE)),
    MN(new Country("Mongolia", "", "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg", Continent.ASIE)),
    MH(new Country("Marshall Islands", "", "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg", Continent.OCEANIE)),
    MK(new Country("Macedonia", "", "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg", Continent.EUROPE)),
    MU(new Country("Mauritius", "", "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg", Continent.AFRIQUE)),
    MT(new Country("Malta", "", "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg", Continent.EUROPE)),
    MW(new Country("Malawi", "", "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg", Continent.AFRIQUE)),
    MV(new Country("Maldives", "", "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg?uselang=fr", Continent.ASIE)),
    MR(new Country("Mauritania", "", "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg", Continent.AFRIQUE)),
    UG(new Country("Uganda", "", "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg", Continent.AFRIQUE)),
    TZ(new Country("Tanzania", "", "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg", Continent.AFRIQUE)),
    MY(new Country("Malaysia", "", "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg", Continent.ASIE)),
    MX(new Country("Mexico", "", "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg", Continent.AMERIQUE)),
    IL(new Country("Israel", "", "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg", Continent.ASIE)),
    FR(new Country("France", "", "https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg?uselang=fr", Continent.EUROPE)),
    FI(new Country("Finland", "", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg", Continent.EUROPE)),
    FJ(new Country("Fiji", "", "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg", Continent.OCEANIE)),
    FM(new Country("Micronesia", "", "https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg", Continent.OCEANIE)),
    NI(new Country("Nicaragua", "", "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg", Continent.AMERIQUE)),
    NL(new Country("Netherlands", "", "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg", Continent.EUROPE)),
    NO(new Country("Norway", "", "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg", Continent.EUROPE)),
    NA(new Country("Namibia", "", "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg", Continent.AFRIQUE)),
    VU(new Country("Vanuatu", "", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg", Continent.OCEANIE)),
    NE(new Country("Niger", "", "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg", Continent.AFRIQUE)),
    NG(new Country("Nigeria", "", "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg", Continent.AFRIQUE)),
    NZ(new Country("New Zealand", "", "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg", Continent.OCEANIE)),
    NP(new Country("Nepal", "", "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg", Continent.ASIE)),
    NR(new Country("Nauru", "", "https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg", Continent.OCEANIE)),
    XK(new Country("Kosovo", "", "https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_Kosovo.svg", Continent.EUROPE)),
    CI(new Country("Ivory Coast", "", "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg?uselang=fr", Continent.AFRIQUE)),
    CH(new Country("Switzerland", "", "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg", Continent.EUROPE)),
    CO(new Country("Colombia", "", "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg", Continent.AMERIQUE)),
    CN(new Country("China", "", "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg?uselang=fr", Continent.ASIE)),
    CM(new Country("Cameroon", "", "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg?uselang=fr", Continent.AFRIQUE)),
    CL(new Country("Chile", "", "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg?uselang=fr", Continent.AMERIQUE)),
    CA(new Country("Canada", "", "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg?uselang=fr", Continent.AMERIQUE)),
    CG(new Country("Republic of the Congo", "", "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg?uselang=fr", Continent.AFRIQUE)),
    CF(new Country("Central African Republic", "", "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg?uselang=fr", Continent.AFRIQUE)),
    CD(new Country("Democratic Republic of the Congo", "", "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg?uselang=fr", Continent.AFRIQUE)),
    CZ(new Country("Czech Republic", "", "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg", Continent.EUROPE)),
    CY(new Country("Cyprus", "", "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg", Continent.EUROPE)),
    CR(new Country("Costa Rica", "", "https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg?uselang=fr", Continent.AMERIQUE)),
    CU(new Country("Cuba", "", "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg", Continent.AMERIQUE)),
    SY(new Country("Syria", "", "https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg", Continent.ASIE)),
    KG(new Country("Kyrgyzstan", "", "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg", Continent.ASIE)),
    KE(new Country("Kenya", "", "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg", Continent.AFRIQUE)),
    SS(new Country("South Sudan", "", "https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg", Continent.AFRIQUE)),
    SR(new Country("Suriname", "", "https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg", Continent.AMERIQUE)),
    KI(new Country("Kiribati", "", "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg", Continent.OCEANIE)),
    KH(new Country("Cambodia", "", "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg", Continent.ASIE)),
    KM(new Country("Comoros", "", "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg", Continent.AFRIQUE)),
    ST(new Country("Sao Tome and Principe", "", "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Sao_Tome_and_Principe.svg", Continent.AFRIQUE)),
    SK(new Country("Slovakia", "", "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg", Continent.EUROPE)),
    KR(new Country("South Korea", "", "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg?uselang=fr", Continent.ASIE)),
    SI(new Country("Slovenia", "", "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg", Continent.EUROPE)),
    KP(new Country("North Korea", "", "https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg?uselang=fr", Continent.ASIE)),
    KW(new Country("Kuwait", "", "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg", Continent.ASIE)),
    SN(new Country("Senegal", "", "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg", Continent.AFRIQUE)),
    SM(new Country("San Marino", "", "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg", Continent.EUROPE)),
    SL(new Country("Sierra Leone", "", "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg", Continent.AFRIQUE)),
    SC(new Country("Seychelles", "", "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg", Continent.AFRIQUE)),
    KZ(new Country("Kazakhstan", "", "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg", Continent.ASIE)),
    SG(new Country("Singapore", "", "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg", Continent.ASIE)),
    SE(new Country("Sweden", "", "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Sweden.svg", Continent.EUROPE)),
    SD(new Country("Sudan", "", "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg", Continent.AFRIQUE)),
    DO(new Country("Dominican Republic", "", "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg?uselang=fr", Continent.AMERIQUE)),
    DM(new Country("Dominica", "", "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg", Continent.AMERIQUE)),
    DJ(new Country("Djibouti", "", "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg", Continent.AFRIQUE)),
    DK(new Country("Denmark", "", "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg?uselang=fr", Continent.EUROPE)),
    DE(new Country("Germany", "", "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg?uselang=fr", Continent.EUROPE)),
    YE(new Country("Yemen", "", "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg", Continent.ASIE)),
    DZ(new Country("Algeria", "", "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg?uselang=fr", Continent.AFRIQUE)),
    US(new Country("United States", "", "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg", Continent.AMERIQUE)),
    UY(new Country("Uruguay", "", "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg", Continent.AMERIQUE)),
    LB(new Country("Lebanon", "", "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg", Continent.ASIE)),
    LC(new Country("Saint Lucia", "", "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg", Continent.AMERIQUE)),
    LA(new Country("Laos", "", "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg", Continent.OCEANIE)),
    TV(new Country("Tuvalu", "", "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg", Continent.OCEANIE)),
    TT(new Country("Trinidad and Tobago", "", "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg", Continent.AMERIQUE)),
    TR(new Country("Turkey", "", "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg", Continent.ASIE)),
    LK(new Country("Sri Lanka", "", "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg", Continent.ASIE)),
    LI(new Country("Liechtenstein", "", "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg", Continent.EUROPE)),
    LV(new Country("Latvia", "", "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg", Continent.EUROPE)),
    TO(new Country("Tonga", "", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg", Continent.AFRIQUE)),
    LT(new Country("Lithuania", "", "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg", Continent.EUROPE)),
    LU(new Country("Luxembourg", "", "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg?uselang=fr", Continent.EUROPE)),
    LR(new Country("Liberia", "", "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg?uselang=fr", Continent.AFRIQUE)),
    LS(new Country("Lesotho", "", "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg", Continent.AFRIQUE)),
    TH(new Country("Thailand", "", "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg", Continent.ASIE)),
    TG(new Country("Togo", "", "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg", Continent.AFRIQUE)),
    TD(new Country("Chad", "", "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg", Continent.AFRIQUE)),
    LY(new Country("Libya", "", "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg", Continent.AFRIQUE)),
    VA(new Country("Vatican", "", "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_the_Vatican_City.svg", Continent.EUROPE)),
    VC(new Country("Saint Vincent and the Grenadines", "", "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg", Continent.AMERIQUE)),
    AE(new Country("United Arab Emirates", "", "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg?uselang=fr", Continent.ASIE)),
    AD(new Country("Andorra", "", "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg?uselang=fr", Continent.EUROPE)),
    AG(new Country("Antigua and Barbuda", "", "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg?uselang=fr", Continent.AMERIQUE)),
    AF(new Country("Afghanistan", "", "https://upload.wikimedia.org/wikipedia/commons/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg", Continent.ASIE)),
    IS(new Country("Iceland", "", "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg?uselang=fr", Continent.EUROPE)),
    IR(new Country("Iran", "", "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg?uselang=fr", Continent.ASIE)),
    AM(new Country("Armenia", "", "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg?uselang=fr", Continent.ASIE)),
    AL(new Country("Albania", "", "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg", Continent.EUROPE)),
    AO(new Country("Angola", "", "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg?uselang=fr", Continent.AFRIQUE)),
    //AS(new Country("American Samoa", "", "Samoa", Continent.OCEANIE)),
    CV(new Country("Cape Verde","", "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg?uselang=fr", Continent.AFRIQUE)),
    AR(new Country("Argentina", "", "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg?uselang=fr", Continent.AMERIQUE)),
    AU(new Country("Australia", "", "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg?uselang=fr", Continent.OCEANIE)),
    AT(new Country("Austria", "", "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg?uselang=fr", Continent.EUROPE)),
    IN(new Country("India", "", "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_India.svg?uselang=fr", Continent.ASIE)),
    AZ(new Country("Azerbaijan", "", "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg?uselang=fr", Continent.ASIE)),
    IE(new Country("Ireland", "", "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg", Continent.EUROPE)),
    ID(new Country("Indonesia", "", "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg?uselang=fr", Continent.ASIE)),
    UA(new Country("Ukraine", "", "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg", Continent.EUROPE)),
    QA(new Country("Qatar", "", "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg", Continent.ASIE)),
    MZ(new Country("Mozambique", "", "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg", Continent.AFRIQUE)),
    EW(new Country("Eswatini", "", "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg", Continent.AFRIQUE));
    //WF(new Country("Wallis and Futuna", Continent.)),
    //sc : nieves https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg
    //BL(new Country("Saint Barthelemy", Continent.)),
    //BM(new Country("Bermuda", Continent.)),
    //BV(new Country("Bouvet Island", Continent.)),
    //BQ(new Country("Bonaire, Saint Eustatius and Saba", Continent.)),
    //JE(new Country("Jersey", Continent.)),
    //RE(new Country("Reunion","", Continent.)),
    //TK(new Country("Tokelau","", Continent.)),
    //GU(new Country("Guam","", Continent.)),
    //GS(new Country("South Georgia and the South Sandwich Islands","", Continent.)),
    //GP(new Country("Guadeloupe","Guadeloupe", Continent.)),
    //GG(new Country("Guernsey","", Continent.)),
    //GF(new Country("French Guiana","Guyane", Continent.)),
    //GL(new Country("Greenland","Groenland", Continent.)),
    //GI(new Country("Gibraltar","", Continent.)),
    //HK(new Country("Hong Kong","", Continent.)),
    //HM(new Country("Heard Island and McDonald Islands","", Continent.)),
    //PR(new Country("Puerto Rico","Porto rico", Continent.)),
    //SJ(new Country("Svalbard and Jan Mayen","", Continent.)),
    //PF(new Country("French Polynesia","Polynesie française", Continent.)),
    //PN(new Country("Pitcairn","", Continent.)),
    //PM(new Country("Saint Pierre and Miquelon","", Continent.)),
    //EH(new Country("Western Sahara","", Continent.)),
    //MF(new Country("Saint Martin","", Continent.)),
    //MO(new Country("Macao","", Continent.)),
    //MQ(new Country("Martinique","Martinique", Continent.)),
    //MP(new Country("Northern Mariana Islands","", Continent.)),
    //MS(new Country("Montserrat","", Continent.)),
    //IM(new Country("Isle of Man","", Continent.)),
    //IO(new Country("British Indian Ocean Territory","", Continent.)),
    //SH(new Country("Saint Helena","", Continent.)),
    //FK(new Country("Falkland Islands","", Continent.)),
    //FO(new Country("Faroe Islands","", Continent.)),
    //NC(new Country("New Caledonia","Nouvelle caledonie", Continent.)),
    //NF(new Country("Norfolk Island","", Continent.)),
    //NU(new Country("Niue","", Continent.)),
    //CK(new Country("Cook Islands","", Continent.)),
    //CC(new Country("Cocos Islands","", Continent.)),
    //CX(new Country("Christmas Island","", Continent.)),
    //CW(new Country("Curacao","", Continent.)),
    //SZ(new Country("Swaziland","", Continent.)),
    //SX(new Country("Sint Maarten","", Continent.)),
    //KN(new Country("Saint Kitts and Nevis","", Continent.)),
    //KY(new Country("Cayman Islands","", Continent.)),
    //VG(new Country("British Virgin Islands","", Continent.)),
    //YT(new Country("Mayotte","Mayotte", Continent.)),
    //UM(new Country("United States Minor Outlying Islands","", Continent.)),
    //TW(new Country("Taiwan","Taiwan", Continent.)),
    //TF(new Country("French Southern Territories","", Continent.)),
    //TC(new Country("Turks and Caicos Islands","", Continent).)
    //AI(new Country("Anguilla","", Continent.)),
    //VI(new Country("U.S.Virgin Islands","", Continent.)),
    //AQ(new Country("Antarctica","Antartique", Continent.)),
    //AW(new Country("Aruba","", Continent.)),
    //AX(new Country("Aland Islands","", Continent.)),

    private final Country country;

    CountriesList(Country country) {
        this.country = country;
    }

    public Country getCountry() {
        return country;
    }
}
